### ISSUE TITLE
Shkarbuta Homework 5.

### ISSUE THREAD

**Issue by alexshk76** [WEB-road/Shkarbuta_Homework5#1]

**Comment by Appof** [comment]
- Скрипти краще підключати в кінці сторніки перед закриваючим тегом body https://github.com/WEB-road/Shkarbuta_Homework5/blob/2050013091a4763d932bb3dca6164eb56f8ac08c/index.html#L26-L44
- Краще прибрати, документ не треба обмежувати в ширині і висоті. Плюс відступи дають чорні полоси по бокам сторінки https://github.com/WEB-road/Shkarbuta_Homework5/blob/2050013091a4763d932bb3dca6164eb56f8ac08c/css/style.css#L66-L67
- на 1193 пкс з'являється чорний простір з правого боку
- також на 980
- на мобільній версії є чорний простір навкруг сторінки, треба прибрати
- на малих екранах такий елемент може стати вже в колонку або просто прибрати картинки https://github.com/WEB-road/Shkarbuta_Homework5/blob/2050013091a4763d932bb3dca6164eb56f8ac08c/css/style.css#L470

**Comment by alexshk76** [comment]
Пофіксив, чекаю на коменти. Дякую.

**Comment by Appof** [comment]
На мобільній версії секцію about можна відцентрувати, щоб не прилипала до країв. А так все гуд

**Comment by alexshk76** [comment]
Пофіксив, якщо правильно зрозумів,  чекаю на коменти. Дякую.
